name = "Dartis-Craft AxB Kinpack"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de83719823c00ffe15cc5a418a9948b9692be6d9ef5b5751905fa2f374f28f9d"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
